name: PIP

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.platform }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.12", "pypy-3.9"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Test
        run: pytest --cov=neo --cov-branch

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
